# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Structure.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Enum_pb2 as Enum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Structure.proto',
  package='',
  syntax='proto2',
  serialized_options=b'H\001',
  serialized_pb=b'\n\x0fStructure.proto\x1a\nEnum.proto\"H\n\x0cRoomUserInfo\x12\x10\n\x08var_name\x18\x01 \x01(\x0c\x12\x11\n\tvar_index\x18\x02 \x01(\x03\x12\x13\n\x0bpicture_uri\x18\x03 \x01(\x0c\"_\n\tRoomInfo2\x12\x0e\n\x06var_id\x18\x01 \x01(\x05\x12\x10\n\x08var_name\x18\x02 \x01(\x0c\x12\x19\n\x11var_current_count\x18\x03 \x01(\x05\x12\x15\n\rvar_max_count\x18\x04 \x01(\x05\"\xae\x01\n\x04Rank\x12\x10\n\x08var_rank\x18\x01 \x01(\x05\x12\x10\n\x08var_name\x18\x02 \x01(\x0c\x12\x11\n\tvar_level\x18\x03 \x01(\x05\x12\x13\n\x0bvar_pic_uri\x18\x04 \x01(\x0c\x12\x11\n\tvar_index\x18\x05 \x01(\x03\x12\x0f\n\x07var_win\x18\x06 \x01(\x05\x12\x10\n\x08var_lose\x18\x07 \x01(\x05\x12\x10\n\x08var_draw\x18\x08 \x01(\x05\x12\x12\n\nvar_contry\x18\t \x01(\x0c\"1\n\x08PrayInfo\x12\x10\n\x08var_name\x18\x01 \x01(\x0c\x12\x13\n\x0bvar_message\x18\x02 \x01(\x0c\x42\x02H\x01'
  ,
  dependencies=[Enum__pb2.DESCRIPTOR,])




_ROOMUSERINFO = _descriptor.Descriptor(
  name='RoomUserInfo',
  full_name='RoomUserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='var_name', full_name='RoomUserInfo.var_name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_index', full_name='RoomUserInfo.var_index', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='picture_uri', full_name='RoomUserInfo.picture_uri', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=103,
)


_ROOMINFO2 = _descriptor.Descriptor(
  name='RoomInfo2',
  full_name='RoomInfo2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='var_id', full_name='RoomInfo2.var_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_name', full_name='RoomInfo2.var_name', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_current_count', full_name='RoomInfo2.var_current_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_max_count', full_name='RoomInfo2.var_max_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=200,
)


_RANK = _descriptor.Descriptor(
  name='Rank',
  full_name='Rank',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='var_rank', full_name='Rank.var_rank', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_name', full_name='Rank.var_name', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_level', full_name='Rank.var_level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_pic_uri', full_name='Rank.var_pic_uri', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_index', full_name='Rank.var_index', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_win', full_name='Rank.var_win', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_lose', full_name='Rank.var_lose', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_draw', full_name='Rank.var_draw', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_contry', full_name='Rank.var_contry', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=377,
)


_PRAYINFO = _descriptor.Descriptor(
  name='PrayInfo',
  full_name='PrayInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='var_name', full_name='PrayInfo.var_name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_message', full_name='PrayInfo.var_message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=428,
)

DESCRIPTOR.message_types_by_name['RoomUserInfo'] = _ROOMUSERINFO
DESCRIPTOR.message_types_by_name['RoomInfo2'] = _ROOMINFO2
DESCRIPTOR.message_types_by_name['Rank'] = _RANK
DESCRIPTOR.message_types_by_name['PrayInfo'] = _PRAYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoomUserInfo = _reflection.GeneratedProtocolMessageType('RoomUserInfo', (_message.Message,), {
  'DESCRIPTOR' : _ROOMUSERINFO,
  '__module__' : 'Structure_pb2'
  # @@protoc_insertion_point(class_scope:RoomUserInfo)
  })
_sym_db.RegisterMessage(RoomUserInfo)

RoomInfo2 = _reflection.GeneratedProtocolMessageType('RoomInfo2', (_message.Message,), {
  'DESCRIPTOR' : _ROOMINFO2,
  '__module__' : 'Structure_pb2'
  # @@protoc_insertion_point(class_scope:RoomInfo2)
  })
_sym_db.RegisterMessage(RoomInfo2)

Rank = _reflection.GeneratedProtocolMessageType('Rank', (_message.Message,), {
  'DESCRIPTOR' : _RANK,
  '__module__' : 'Structure_pb2'
  # @@protoc_insertion_point(class_scope:Rank)
  })
_sym_db.RegisterMessage(Rank)

PrayInfo = _reflection.GeneratedProtocolMessageType('PrayInfo', (_message.Message,), {
  'DESCRIPTOR' : _PRAYINFO,
  '__module__' : 'Structure_pb2'
  # @@protoc_insertion_point(class_scope:PrayInfo)
  })
_sym_db.RegisterMessage(PrayInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
