// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Enum.proto</summary>
public static partial class EnumReflection {

  #region Descriptor
  /// <summary>File descriptor for Enum.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EnumReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpFbnVtLnByb3RvKqYGCghQUk9UT0NPTBIWChJJRF9QS1RfVkVSU0lPTl9S",
          "RVEQABIWChJJRF9QS1RfVkVSU0lPTl9SRVMQARIUChBJRF9QS1RfTE9HSU5f",
          "UkVREAISFAoQSURfUEtUX0xPR0lOX1JFUxADEhoKFklEX1BLVF9DUkVBVEVf",
          "Uk9PTV9SRVEQBBIaChZJRF9QS1RfQ1JFQVRFX1JPT01fUkVTEAUSGQoVSURf",
          "UEtUX0VOVEVSX1JPT01fUkVREAYSGQoVSURfUEtUX0VOVEVSX1JPT01fUkVT",
          "EAcSGQoVSURfUEtUX0xFQVZFX1JPT01fUkVREAgSGQoVSURfUEtUX0xFQVZF",
          "X1JPT01fUkVTEAkSHQoZSURfUEtUX0JJVE1BUF9NRVNTQUdFX1JFURAKEh0K",
          "GUlEX1BLVF9CSVRNQVBfTUVTU0FHRV9SRVMQCxIfChtJRF9QS1RfTkVXX1VT",
          "RVJfSU5fUk9PTV9OVFkQDBIYChRJRF9QS1RfUk9PTV9MSVNUX1JFURANEhgK",
          "FElEX1BLVF9ST09NX0xJU1RfUkVTEA4SGQoVSURfUEtUX0dBTUVfU1RBUlRf",
          "TlRZEA8SGgoWSURfUEtUX0dBTUVfUkVTVUxUX05UWRAQEiAKHElEX1BLVF9S",
          "T09NX1BBU1NfVEhST1VHSF9SRVEQERIgChxJRF9QS1RfUk9PTV9QQVNTX1RI",
          "Uk9VR0hfUkVTEBISFQoRSURfUEtUX05PVElDRV9SRVEQExIVChFJRF9QS1Rf",
          "Tk9USUNFX1JFUxAUEhwKGElEX1BLVF9BVURJT19NRVNTQUdFX1JFURAVEhwK",
          "GElEX1BLVF9BVURJT19NRVNTQUdFX1JFUxAWEhsKF0lEX1BLVF9QUkFZX01F",
          "U1NBR0VfUkVREBcSGwoXSURfUEtUX1BSQVlfTUVTU0FHRV9SRVMQGBIfChtJ",
          "RF9QS1RfUFJBWV9NRVNTQUdFX1JFR19SRVEQGRIfChtJRF9QS1RfUFJBWV9N",
          "RVNTQUdFX1JFR19SRVMQGhISCg5JRF9QS1RfUU5BX1JFURAbEhIKDklEX1BL",
          "VF9RTkFfUkVTEBwqYQoJRXJyb3JDb2RlEgsKB1N1Y2Nlc3MQABIRCg1EYXRh",
          "QmFzZUVycm9yEAESEgoOTG9naW5EdXBsaWNhdGUQAhIPCgtTeXN0ZW1FcnJv",
          "chADEg8KC0xvZ2luRmFpbGVkEARCAkgBYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PROTOCOL), typeof(global::ErrorCode), }, null, null));
  }
  #endregion

}
#region Enums
public enum PROTOCOL {
  [pbr::OriginalName("ID_PKT_VERSION_REQ")] IdPktVersionReq = 0,
  [pbr::OriginalName("ID_PKT_VERSION_RES")] IdPktVersionRes = 1,
  [pbr::OriginalName("ID_PKT_LOGIN_REQ")] IdPktLoginReq = 2,
  [pbr::OriginalName("ID_PKT_LOGIN_RES")] IdPktLoginRes = 3,
  [pbr::OriginalName("ID_PKT_CREATE_ROOM_REQ")] IdPktCreateRoomReq = 4,
  [pbr::OriginalName("ID_PKT_CREATE_ROOM_RES")] IdPktCreateRoomRes = 5,
  [pbr::OriginalName("ID_PKT_ENTER_ROOM_REQ")] IdPktEnterRoomReq = 6,
  [pbr::OriginalName("ID_PKT_ENTER_ROOM_RES")] IdPktEnterRoomRes = 7,
  [pbr::OriginalName("ID_PKT_LEAVE_ROOM_REQ")] IdPktLeaveRoomReq = 8,
  [pbr::OriginalName("ID_PKT_LEAVE_ROOM_RES")] IdPktLeaveRoomRes = 9,
  [pbr::OriginalName("ID_PKT_BITMAP_MESSAGE_REQ")] IdPktBitmapMessageReq = 10,
  [pbr::OriginalName("ID_PKT_BITMAP_MESSAGE_RES")] IdPktBitmapMessageRes = 11,
  [pbr::OriginalName("ID_PKT_NEW_USER_IN_ROOM_NTY")] IdPktNewUserInRoomNty = 12,
  [pbr::OriginalName("ID_PKT_ROOM_LIST_REQ")] IdPktRoomListReq = 13,
  [pbr::OriginalName("ID_PKT_ROOM_LIST_RES")] IdPktRoomListRes = 14,
  [pbr::OriginalName("ID_PKT_GAME_START_NTY")] IdPktGameStartNty = 15,
  [pbr::OriginalName("ID_PKT_GAME_RESULT_NTY")] IdPktGameResultNty = 16,
  [pbr::OriginalName("ID_PKT_ROOM_PASS_THROUGH_REQ")] IdPktRoomPassThroughReq = 17,
  [pbr::OriginalName("ID_PKT_ROOM_PASS_THROUGH_RES")] IdPktRoomPassThroughRes = 18,
  [pbr::OriginalName("ID_PKT_NOTICE_REQ")] IdPktNoticeReq = 19,
  [pbr::OriginalName("ID_PKT_NOTICE_RES")] IdPktNoticeRes = 20,
  [pbr::OriginalName("ID_PKT_AUDIO_MESSAGE_REQ")] IdPktAudioMessageReq = 21,
  [pbr::OriginalName("ID_PKT_AUDIO_MESSAGE_RES")] IdPktAudioMessageRes = 22,
  [pbr::OriginalName("ID_PKT_PRAY_MESSAGE_REQ")] IdPktPrayMessageReq = 23,
  [pbr::OriginalName("ID_PKT_PRAY_MESSAGE_RES")] IdPktPrayMessageRes = 24,
  [pbr::OriginalName("ID_PKT_PRAY_MESSAGE_REG_REQ")] IdPktPrayMessageRegReq = 25,
  [pbr::OriginalName("ID_PKT_PRAY_MESSAGE_REG_RES")] IdPktPrayMessageRegRes = 26,
  [pbr::OriginalName("ID_PKT_QNA_REQ")] IdPktQnaReq = 27,
  [pbr::OriginalName("ID_PKT_QNA_RES")] IdPktQnaRes = 28,
}

public enum ErrorCode {
  [pbr::OriginalName("Success")] Success = 0,
  [pbr::OriginalName("DataBaseError")] DataBaseError = 1,
  [pbr::OriginalName("LoginDuplicate")] LoginDuplicate = 2,
  [pbr::OriginalName("SystemError")] SystemError = 3,
  [pbr::OriginalName("LoginFailed")] LoginFailed = 4,
}

#endregion


#endregion Designer generated code
